version: "3.7"

networks:
  kong-net:
    name: kong-net
    driver: bridge

services:
  financeback:
    image: lucasorramon/financeback:0.0.5
    restart: always
    networks:
      - kong-net
    ports:
      - 8081:8080
    depends_on:
      - mongodb
      
  financefront:
    build: ./finance_front
    restart: always
    ports:
      - 8082:8000
    networks:
      - kong-net
  
  mongodb:
    image: bitnami/mongodb:5.0
    restart: always
    ports:
      - 27017:27017
    networks:
      - kong-net

  mongoseed:
    image: bitnami/mongodb:5.0
    volumes:
      - ./mongo:/mongo
    command: >
       bash -c "mongoimport --host mongodb --db finance --collection revenue --drop --type json --file /mongo/revenue.json --jsonArray && 
       mongoimport --host mongodb --db finance --collection expenditure --drop --type json --file /mongo/expenditure.json --jsonArray"
    networks:
      - kong-net
    depends_on:
      - mongodb